version: '3.7'

services:

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/dlm
    env_file:
      - devops/common.env

  redis:
    image: redis:5.0.7-alpine
    ports:
      - target: 6379
        published: 6379
    expose:
      - 6379
          